class Invoice {
  String? id;
  String? customerId;
  String? axSalesId;
  DateTime? invoiceDate;
  DateTime? dueDate;
  DateTime? documentDate;
  int? quantity;
  double? volume;
  double? weight;
  double? salesBalance;
  double? vat;
  double? invoiceAmount;
  String? salesAdministrator;
  String? salesUnitId;
  String? salesRepId;
  String? department;
  String? deliveryName;
  String? deliveryAddress;
  String? deleveryZipCode;
  String? invoicingName;
  String? invoicingAddress;
  String? invoicingZipCode;
  String? customerRef;
  String? bpcCustomerRef;
  String? bpcMessage;
  DateTime? bpcInvoiceRecieptAt;
  DateTime? bpcInvoiceCompletedAt;
  String? bpcBillCollector;
  DateTime? createdAt;
  int? overDueDays;

  Invoice({
    required this.id,
    required this.customerId,
    required this.axSalesId,
    required this.invoiceDate,
    required this.dueDate,
    required this.documentDate,
    required this.quantity,
    required this.volume,
    required this.weight,
    required this.salesBalance,
    required this.vat,
    required this.invoiceAmount,
    required this.salesAdministrator,
    required this.salesUnitId,
    required this.salesRepId,
    required this.department,
    required this.deliveryName,
    required this.deliveryAddress,
    required this.deleveryZipCode,
    required this.invoicingName,
    required this.invoicingAddress,
    required this.invoicingZipCode,
    required this.customerRef,
    required this.bpcCustomerRef,
    required this.bpcMessage,
    required this.bpcInvoiceRecieptAt,
    required this.bpcInvoiceCompletedAt,
    required this.bpcBillCollector,
    required this.createdAt,
    required this.overDueDays,
  });
}
