# This is a basic workflow to help you get started with Actions

name: Build APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: '3.10.4'
    - run: flutter pub get
    - run: flutter build appbundle
    
    # Upload generated apk to the artifacts.
    # - uses: actions/upload-artifact@v1
    #  with:
    #    name: release
    #    path: build/app/outputs/apk/release/app-release.apk